[package]
name = "lyra-stream-client"
description = "gRPC client for the Lyra stream service."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lyra-stream-proto = { path = "../proto" }
async-trait = { workspace = true }
backoff = { workspace = true }
dashmap = { workspace = true }
futures-util = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
