[package]
name = "liblyra"
version = "0.1.0"
edition = "2024"
resolver = "3"

[dependencies]
meta = { path = "../../lyrad/meta" }
async-trait = { workspace = true }
thiserror = { workspace = true }
futures-util = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
dashmap = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
backoff = { version = "0.4", features = ["tokio"] }
