syntax = "proto3";

package io.lyra.proto.ext.v1;


enum StatusCode {
  OK = 0;
  INVALID_TERM = 1;
  FENCED = 2;
}

// control commands
message FenceRequest {
  int64 stream_id = 1;
  int64 term = 2;
}

message FenceResponse {
  StatusCode code = 1;
  int64 lra = 2;
  int64 term = 3;
}


message Event {
  int64 stream_id = 1;
  int64 term = 2;
  int64 offset = 3;
  optional bytes payload = 4;
  optional uint32 crc32 = 5;
  int64 timestamp = 6;
  int64 schema_id = 7;
}

message ReadEventsRequest {
  int64 stream_id = 1;
  int64 start_offset = 2;
  int64 end_offset = 3;
}

enum ChunkType {
  FULL = 0;
  FIRST = 1;
  MIDDLE = 2;
  LAST = 3;
}

// streaming
message ReadEventsResponse {
  StatusCode code = 1;
  ChunkType type = 2;
  int64 stream_id = 3;
  repeated Event event = 4;
  int64 advanced_offset = 5;
}

// batching operations
message AppendEventsRequest {
  repeated AppendEventsRequestItem items = 1;
}

message AppendEventsRequestItem {
  Event event = 1;
  bool trunc = 2;
  int64 lra = 3;
}

message AppendEventsResponse {
  StatusCode code = 1;
  int64 commit_offset = 2;
  int64 stream_id = 3;
  int64 term = 4;
}

service Lyra {
  rpc Append(stream AppendEventsRequest) returns (stream AppendEventsResponse);
  rpc Read(stream ReadEventsRequest) returns (stream ReadEventsResponse);
  rpc Fence(FenceRequest) returns (FenceResponse);
}
